baseURL = "https://fuggint.com/"
title = "FUGGINT"
theme = "stack"
languageCode = "en-us"

[services]
  [services.googleAnalytics]
    ID = ""

[params.sidebar]
subtitle = "Threat Intelligence & Hunting"

[params.sidebar.avatar]
enabled = true
src = "/img/avatar.png"
alt = "Portrait of Tommy Fugger"