baseURL = "https://fuggint.com/"
title = "FUGGINT"
theme = "stack"
languageCode = "en-us"

[services]
  [services.googleAnalytics]
    ID = ""

[params.sidebar]
subtitle = "Threat Hunting & Intelligence"

[params.sidebar.avatar]
enabled = true
src = "/img/avatar.png"
alt = "Portrait of Tommy Fugger"


[[menu.main]]
name = "Connect with Me!"
url = "https://www.linkedin.com/in/tsfugger/"
weight = 50

  [menu.main.params]
  newTab = true
  icon = "brand-linkedin"


[params]
favicon = "/favicon.ico"
